# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KYGDz9fXABndU59Uv5el_3wrCMAvaUnk
"""

# Bubble Sort Simulation App

## Demo screenshot
(Add a screenshot/GIF after running locally)

## Problem Breakdown & Computational Thinking
- **Decomposition:** Repeatedly compare adjacent elements and swap if needed.
- **Pattern Recognition:** Each pass pushes the largest remaining element to the end.
- **Abstraction:** Hide indices; show steps as list states.
- **Algorithm Design:** Input (CSV numbers) → Bubble Sort steps → Output (steps + final sorted list).

### Flowchart (text outline)
Start → Input List → Outer Loop → Inner Loop → Compare → Decision (Swap?) → Record Step → Repeat → Output Sorted List → End

## Steps to run
1. Install:
   ```bash
   pip install -r requirements.txt