# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KYGDz9fXABndU59Uv5el_3wrCMAvaUnk
"""

gradio==4.0.0