# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/103Ri42wSBzjzwyvDI8OcGLy-G8Or4IzE
"""

import gradio as gr

# Bubble Sort implementation with step tracking
def bubble_sort_steps(input_list):
    steps = []
    arr = input_list.copy()
    n = len(arr)
    for i in range(n):
        for j in range(0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
            steps.append(arr.copy())  # record each step
    return steps

# Function for Gradio interface
def simulate_sort(numbers):
    try:
        # Convert comma-separated string into list of integers
        arr = [int(x.strip()) for x in numbers.split(",")]
    except ValueError:
        return "False Please enter integers separated by commas."

    steps = bubble_sort_steps(arr)
    output = ""
    for idx, step in enumerate(steps):
        output += f"Step {idx+1}: {step}\n"
    output += f"\n Final Sorted List: {steps[-1]}"
    return output

# Gradio UI
demo = gr.Interface(
    fn=simulate_sort,
    inputs=gr.Textbox(label="Enter numbers (comma-separated)", placeholder="e.g. 5, 3, 8, 1"),
    outputs="text",
     title="Bubble Sort Simulation",
    description="Interactive Bubble Sort demo. Enter a list of numbers to see step-by-step sorting."
)

if __name__ == "__main__":
    demo.launch()